### PR TITLE
fix: ctrl-c doesn't restore cursor

### LINKED ISSUE #74: ctrl-c doesn't restore cursor after `Select::run`
Running `cargo run --example select` and pressing ctrl-c doesn't restore the cursor of the terminal:

[Screencast 2024-12-17 16:12:54.webm](https://github.com/user-attachments/assets/abbc2de9-cae9-4644-b859-3f26c91252b6)

All of the following provided examples have the same problem:
- `input`
- `input-password`
- `list`
- `multiselect`
- `multiselect_huge`
- `select`
- `spinner`
- `spinner-prompts`
- `themes`

### PR DESCRIPTION
**Pull request by roele**
Fixes #74 

- Confirm/Dialog currently don't hide the cursor which i think they should
- IMO behaviour of Escape and CTRL+C should be the same and not clear the terminal
- not sure about the current Spinner behaviour though

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -24,3 +25,12 @@ mod theme;
 
 #[cfg(test)]
 mod test;
+
+/// Resets the cursor when a user presses `Ctrl+C`.
+/// This is useful when the cursor is hidden and the program is interrupted.
+fn show_cursor_after_ctrlc(term: &Term) {
+    let t = term.clone();
+    let _ = ctrlc::set_handler(move || {
```
Comment (jdx) [inline src/lib.rs:33]: Isn't this going to trap all future ctrlc's after demand is done?

Comment (jdx) [reply src/lib.rs:33]: I believe you can make use of this: https://docs.rs/signal-hook/latest/signal_hook/low_level/fn.unregister.html

It's also important this at least compiles on windows, not sure if we need the cursor logic there or not though. We should at least run ˋcargo build` in GitHub actions on this project.

Comment (roele) [reply src/lib.rs:33]: 🤔 good question, guess i need to dig a bit deeper into this

Comment (jdx) [reply src/lib.rs:33]: Yeah I believe that's why I didn't put it in here when I added it to mise, since in mise I can trap forever. I do think this is doable though

File: src/input.rs [hunk 2]
```diff
@@ -153,6 +154,8 @@ impl<'a> Input<'a> {
     /// This function will block until the user submits the input. If the user cancels the input,
     /// an error of type `io::ErrorKind::Interrupted` is returned.
     pub fn run(mut self) -> io::Result<String> {
+        let ctrlc_handle = ctrlc::show_cursor_after_ctrlc(&self.term)?;
```
Comment (roele) [inline src/input.rs:157]: this approach seems to work more or less but having to close the handle is a bit cumbersome though. it seems a bit safer then using unsafe operations to register/unregister. signal_hooks also probably won't work on Windows as per docs.

@jdx any ideas?

Comment (jdx) [reply src/input.rs:157]: can you even hide the cursor to begin with on windows?

Comment (jdx) [reply src/input.rs:157]: I'll test real quick on my windows laptop

File: Cargo.toml [hunk 3]
```diff
@@ -12,7 +12,9 @@ keywords = ["cli", "prompt", "console"]
 console = "0.15"
 fuzzy-matcher = "0.3"
 itertools = "0.13"
+lazy_static = "1.5.0"
```
Comment (jdx) [inline Cargo.toml:15]: I prefer using Lazy from once_cell

File: src/input.rs [hunk 4]
```diff
@@ -179,12 +182,14 @@ impl<'a> Input<'a> {
...
                         self.term.clear_to_end_of_screen()?;
+                        ctrlc::close_ctrlc_handle(ctrlc_handle);
                         return self.handle_submit();
                     }
                 }
                 Key::Tab => self.handle_tab()?,
                 Key::Escape => {
-                    self.clear()?;
+                    self.term.show_cursor()?;
+                    ctrlc::close_ctrlc_handle(ctrlc_handle);
```
Comment (jdx) [inline src/input.rs:192]: I think the better way to do this would be to `impl Drop` on a struct that `ctrlc::show_cursor` returns so that showing the cursor happens automatically and we don't need to remember to explicitly close. https://doc.rust-lang.org/rust-by-example/trait/drop.html

Comment (jdx) [reply src/input.rs:192]: I think you'll need to wrap ctrlc_handle in a struct like this:

```rust
pub struct CtrlcHandle(Handle);

impl Drop CtrlcHandle {
  fn drop() {
    close_ctrlc_handle(self.0);
  }
}

Comment (roele) [reply src/input.rs:192]: This sounds what i was looking for. So if the variable is going out of scope the handle is closed automatically.

File: src/ctrlc.rs [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+pub fn set_ctrlc_handler<F>(mut handler: F) -> Result<Option<Handle>, Error>
+where
+    F: FnMut() + 'static + Send,
+{
+    let _guard = INIT_LOCK.lock();
+    if INIT.load(Ordering::Relaxed) {
+        let handle_guard = HANDLE.read().unwrap();
+        return Ok(handle_guard.clone());
+    }
+    INIT.store(true, Ordering::Relaxed);
```
[the remark this answers is not in the document]
Comment (jdx) [reply src/ctrlc.rs:46]: ok I tested this and it does seem to work as you described.

As far as the multiple prompts things, I handle this with a mutex in mise: https://github.com/jdx/mise/blob/0f9dae377eaa8a527c099310944e75bac60bc3a3/src/ui/prompt.rs#L13

but we should probably put that in here since it never makes sense to show 2 prompts at the same time

File: src/ctrlc.rs [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+        atomic::{AtomicBool, Ordering},
+        Mutex, RwLock,
+    },
+    thread,
+};
+
+static INIT: AtomicBool = AtomicBool::new(false);
+static INIT_LOCK: Mutex<()> = Mutex::new(());
+
+static HANDLE: Lazy<RwLock<Option<Handle>>> = Lazy::new(|| RwLock::new(None));
```
Comment (jdx) [inline src/ctrlc.rs:19]:
```suggestion
static HANDLE: Lazy<RwLock<Option<Handle>>> = Lazy::new(Default::default);
```

this does the same thing, but if we ever decide to use a different mutex type or something it makes refactoring easier

File: src/ctrlc.rs [hunk 7]
```diff
@@ -0,0 +1,86 @@
...
+        atomic::{AtomicBool, Ordering},
+        Mutex, RwLock,
+    },
+    thread,
+    time::Duration,
+};
+
+static MUTEX: Mutex<()> = Mutex::new(());
+static INIT: AtomicBool = AtomicBool::new(false);
+static HANDLE: Lazy<RwLock<Option<CtrlcHandle>>> = Lazy::new(|| RwLock::new(None));
```
Comment (roele) [inline src/ctrlc.rs:19]: using `Lazy::new(Default::default())` does not seem to work since `Handle` does not implement a default

File: src/ctrlc.rs [hunk 8]
```diff
@@ -0,0 +1,86 @@
...
+    #[allow(dead_code)]
+    pub fn close(&self) {
+        self.0.close();
+    }
+}
+
+impl Drop for CtrlcHandle {
+    fn drop(&mut self) {
+        // let the signal handler finish
+        thread::sleep(Duration::from_millis(100));
```
Comment (roele) [inline src/ctrlc.rs:34]: `drop` works too well and executes even before the closure is called or done executing

File: src/input.rs [hunk 9]
```diff
@@ -153,6 +154,8 @@ impl<'a> Input<'a> {
     /// This function will block until the user submits the input. If the user cancels the input,
     /// an error of type `io::ErrorKind::Interrupted` is returned.
     pub fn run(mut self) -> io::Result<String> {
+        let _ctrlc_handle = ctrlc::show_cursor_after_ctrlc(&self.term)?;
```
Comment (roele) [inline src/input.rs:157]: unused variable is necessary here otherwise the handler is dropped immediately

Comment (jdx) [reply src/input.rs:157]: yes, this is the correct way to write this. I _think_ you can also add `#[must_use]` to enforce that it isn't dropped immediately but I'm not 100% on that

File: src/ctrlc.rs (hunk 8 above)
Comment (jdx) [reply src/ctrlc.rs:34]: hmm might be better to go back to the way you had it before because this might not complete before the CLI stops running

**Comment by jdx** [comment]
you may want to do something like this if you can't get windows to work: https://github.com/jdx/mise/blob/127e1646f80fba36a2b2a1b7956d6d8e77f83c5f/src/ui/mod.rs#L3

**Comment by roele** [comment]
@jdx thanks for the hint, thought i could get it to work within the same file but your approach with a specific stub seems much easier to work with

File: src/input.rs (hunk 2 above)
Comment (roele) [reply src/input.rs:157]: Windows support for signals seems hopeless at this point. The `ctrlc` crate goes a long way to make it happen but theres no way to unregister for our use-case. For now i guess we have to accept this as a known issue.
